# Generated by Django 4.2.2 on 2023-06-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
